export interface Book {
  id: string
  title: string
  author: string
  year?: number
}

export const books: Book[] = [
  { id: "1", title: "Sarajevska knjiga mrtvih", author: "Josip Osti", year: 1993 },
  { id: "2", title: "Vse ljubezni so nenavadne", author: "Josip Osti", year: 2010 },
  { id: "3", title: "Nekaj o nas kot živalih", author: "Tone Škrjanec", year: 2020 },
  { id: "4", title: "Jutro ni bilo v načrtu", author: "Tone Škrjanec", year: 2024 },
  { id: "5", title: "Čuvaj sna", author: "Vinko Möderndorfer", year: 2020 },
  { id: "6", title: "Samota", author: "Vinko Möderndorfer", year: 2023 },
  { id: "7", title: "Vnazaj", author: "Barbara Korun", year: 2024 },
  { id: "8", title: "Pridem takoj", author: "Barbara Korun", year: 2011 },
  { id: "9", title: "Včasih", author: "Esad Babačić", year: 2021 },
  { id: "10", title: "Kiti se ne napihujejo", author: "Esad Babačić", year: 2000 },
  { id: "11", title: "Sloni jočejo pošteno", author: "Esad Babačić", year: 2011 },
  { id: "12", title: "Ostani", author: "Nataša Velikonja", year: 2014 },
  { id: "13", title: "Prostor sred križišč", author: "Nataša Velikonja", year: 2021 },
  { id: "14", title: "Točke izginjanja", author: "Lucija Stupica", year: 2019 },
  { id: "15", title: "Liebestod", author: "Miklavž Komelj", year: 2017 },
  { id: "16", title: "Milijon sekund bliže", author: "Gregor Podlogar", year: 2006 },
  { id: "17", title: "Atlas", author: "Gregor Podlogar", year: 2022 },
  { id: "18", title: "P(l)ast za p(l)astjo", author: "Petra Kolmančič", year: 2014 },
  { id: "19", title: "Vznožje", author: "Stanka Hrastelj", year: 2024 },
  { id: "20", title: "V roki", author: "Anja Zag Golob", year: 2010 },
  { id: "21", title: "Veza v zgibi", author: "Anja Zag Golob", year: 2013 },
  { id: "22", title: "Didaskalije k dihanju", author: "Anja Zag Golob", year: 2016 },
  { id: "23", title: "Da ne da ne bo več prišla da ne bo da me žge …", author: "Anja Zag Golob", year: 2019 },
  { id: "24", title: "Nekajkrat smo zašli, zdaj se vračamo", author: "Miljana Cunta", year: 2023 },
  { id: "25", title: "Privlačnosti", author: "Alja Adam", year: 2020 },
  { id: "26", title: "Tri postaje", author: "Jure Jakob", year: 2009 },
  { id: "27", title: "Lakota", author: "Jure Jakob", year: 2018 },
  { id: "28", title: "Drobne opazke", author: "Jure Jakob", year: 2024 },
  { id: "29", title: "Rumeno gori grm forzicij", author: "Veronika Dintinjana", year: 2008 },
  { id: "30", title: "V suhem doku", author: "Veronika Dintinjana", year: 2016 },
  { id: "31", title: "Metulji pod tlakom", author: "Dejan Koban", year: 2008 },
  { id: "32", title: "Razporeditve", author: "Dejan Koban", year: 2014 },
  { id: "33", title: "Tehno", author: "Ana Pepelnik", year: 2017 },
  { id: "34", title: "Treš", author: "Ana Pepelnik", year: 2021 },
  { id: "35", title: "V drevo", author: "Ana Pepelnik", year: 2024 },
  { id: "36", title: "Seznam", author: "Andrej Hočevar", year: 2017 },
  { id: "37", title: "Selišča", author: "Kristina Kočan", year: 2021 },
  { id: "38", title: "Krčrk", author: "Karlo Hmeljak", year: 2012 },
  { id: "39", title: "Človek pod luno", author: "Blaž Iršič", year: 2019 },
  { id: "40", title: "Parada heteroseksualcev", author: "Blaž Iršič", year: 2025 },
  { id: "41", title: "Ljubav reče greva", author: "Nina Dragičević", year: 2019 },
  { id: "42", title: "To telo, pokončno", author: "Nina Dragičević", year: 2021 },
  { id: "43", title: "Krog", author: "Kaja Teržan", year: 2018 },
  { id: "44", title: "Davek na dodano vrednost", author: "Katja Perat", year: 2014 },
  { id: "45", title: "Fatamorgana", author: "Anja Cimerman", year: 2017 },
  { id: "46", title: "Krhke karavane", author: "Muanis Sinanović", year: 2020 },
  { id: "47", title: "Drseči svet", author: "Nina Medved", year: 2020 },
  { id: "48", title: "Rodna doba", author: "Nina Medved", year: 2024 },
  { id: "49", title: "Negotovosti navkljub", author: "Katarina Gomboc", year: 2018 },
  { id: "50", title: "Dostop na odprto morje", author: "Nina Kremžar", year: 2019 },
  { id: "51", title: "Vejo po vejo", author: "Tanja Božić", year: 2024 },
  { id: "52", title: "Uho", author: "Jan Krmelj", year: 2023 },
  { id: "53", title: "Tuja mehkoba", author: "Natalija Milovanović", year: 2025 },
  { id: "54", title: "Do tu sega gozd", author: "Tom Veber", year: 2021 },
  { id: "55", title: "Kap lje kap lje", author: "Lara Božak", year: 2025 },
  { id: "56", title: "Čisto potiho", author: "Aljaž Primožič", year: 2022 },
  { id: "57", title: "Obronki", author: "Nika Gradišek", year: 2024 },
  { id: "58", title: "Jezik okoliščin", author: "Manca Marinko", year: 2023 },
]
